spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wechat2
    password: HUANhuan_123
    url: jdbc:mysql://192.168.1.31/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    context-path: /onlineStore
