spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: onlineStore
    password: *********
    url: jdbc:mysql://192.168.1.36/onlineStore?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    mode: HTML
  mail:
    host: smtp.gmail.com
    port: 587
    username: maxOnline607
    password: ************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080



